version: 2.1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: dev
jobs:
  build:
    docker:
      - image: node

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - store_artifacts:
          path: ~/repo
